name: CI/CD - Deploy & Healthcheck

on:
  push:
    branches: [ main, master, 'Fix/-Zipkin' ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  deploy-and-check:
    name: Levanta sistema y verifica salud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version || docker-compose version

      - name: Levanta todos los servicios
        run: |
          docker compose up -d

      - name: Espera a que los servicios estén arriba
        run: |
          echo "Esperando 20 segundos para que los servicios arranquen..."
          sleep 20

      - name: Healthcheck frontend
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep 200

      - name: Healthcheck todos-api
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8082/api/todos | grep 200

      - name: Healthcheck log-message-processor
        run: |
          echo "Este servicio no expone endpoint HTTP, omite healthcheck"

      - name: Apaga los servicios
        if: always()
        run: |
          docker compose down
